name: 'DeployHeroku'
on:
  push:
    branches:
      - backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: mtsmachado8/heroku-deploy@v2.0.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile: '/home/runner/work/tech-task-deploy/tech-task-deploy/Dockerfile'





