name: HerokuDeployment

on:
  push:
    branches:
      - backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        id: heroku
        uses: mtsmachado8/heroku-deploy@v1.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          dockerfile_path: 'Dockerfile'